### ISSUE TITLE
Update documentations

### ISSUE THREAD

**Issue by shchae7** [postechsv/tee-formal-spec#2]
Documentations, including README and comments, are either not up to date or require cleanup. Below are some examples that require an update.

- README (lacks repository structure overview)
  - need to provide descriptions of each file.
  - perhaps adapt descriptions from README in https://github.com/postechsv/tee-formal-analysis.
```
...
- Formal model of the TEE infrastructure (in tee-formal-analysis README)
  
  - objects.maude       	: Common storage objects (e.g., superclass object of transient and persistent objects).
  - handle.maude        	: Handle objects. 
  - constants.maude     	: Partial constants described in Global Platform spec.
...
```

- src/app.maude
  - comments that are no longer required need cleanup
```
--- This module defines ree request data structure.
```

**Comment by shchae7** [comment]
There are also wrong comments as well. (Will update this comment as I identify more)

location: src/os.maude
issue: the module TEE-OS defines the Trusted OS, not the execution environments.
```
--- This module defines execution environments for REE and TEE.

omod TEE-OS is
...
```

**Comment by rgyen** [comment]
This issue is resolved now.
