### ISSUE TITLE
Partial spec. of operators restricting benchmark addition

### ISSUE THREAD

**Issue by shchae7** [postechsv/tee-formal-spec#4]
The current model, providing partial specification of operators related to TEE API functions' behavior,
is restricting the ability to analyze other benchmarks effectively.

For example, the following piece of Gatekeeper TA code (mentioned as a candidate for benchmark addition in issue: postechsv/tee-formal-analysis#1)  cannot be analyzed.
```
res = TEE_AllocateTransientObject(TEE_TYPE_HMAC_SHA256, HMAC_SHA256_KEY_SIZE_BIT, &masterKey);
...
TEE_InitRefAttribute(&attrs[0], TEE_ATTR_SECRET_VALUE, secretData, sizeof(secretData));
...
res = TEE_PopulateTransientObject(masterKey, attrs, sizeof(attrs)/sizeof(attrs[0]));
```

This is because the operators responsible for defining the mandatory and allowed attributes for the TEE_PopulateTransientObject function are currently partially defined (in `transient.maude`).
```
op mandatory : ObjectType -> Set{AttrId} .
...
op allowed : ObjectType -> Set{AttrId} .
```

**Comment by rgyen** [comment]
The issue is resolved now.
